# Generated by Django 3.1.3 on 2020-12-10 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='wo_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('isActive', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
            },
        ),
        migrations.CreateModel(
            name='wo_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('isActive', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Active')),
                ('division', models.CharField(blank=True, default='OSP', max_length=10, null=True, verbose_name='Division')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('descriptionDay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descriptionDay', to='workorder.wo_day', verbose_name='Description Day')),
                ('woUser', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'maker'}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='WO User')),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'descriptions',
            },
        ),
        migrations.CreateModel(
            name='wo_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('isActive', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Active')),
                ('progressDay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progressDay', to='workorder.wo_day', verbose_name='Progress Day')),
                ('progressDescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progressDescription', to='workorder.wo_description', verbose_name='Progress Description')),
                ('woBriks', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'briks'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='woBriks', to=settings.AUTH_USER_MODEL, verbose_name='WO BRIKS')),
            ],
            options={
                'verbose_name': 'progress',
                'verbose_name_plural': 'progresss',
            },
        ),
        migrations.CreateModel(
            name='wo_workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('isActive', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Active')),
                ('workorder', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Work Order')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration')),
                ('dueDate', models.DateField(verbose_name='Due Date')),
                ('woChecker', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'checker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='woChecker', to=settings.AUTH_USER_MODEL, verbose_name='WO Checker')),
                ('woMaker', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'maker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='woMaker', to=settings.AUTH_USER_MODEL, verbose_name='WO Maker')),
                ('woSigner', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'signer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='woSigner', to=settings.AUTH_USER_MODEL, verbose_name='WO Signer')),
                ('workorderDay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorderDay', to='workorder.wo_day', verbose_name='Work Order Day')),
                ('workorderDescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorderDescription', to='workorder.wo_description', verbose_name='Work Order Description')),
            ],
            options={
                'verbose_name': 'work order',
                'verbose_name_plural': 'work orders',
            },
        ),
        migrations.CreateModel(
            name='wo_rincian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('isActive', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Active')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('information', models.TextField(blank=True, max_length=500, null=True, verbose_name='Information')),
                ('briksUser', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'briks'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='briksUser', to=settings.AUTH_USER_MODEL, verbose_name='Petugas BRIKS')),
                ('ospUser', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'maker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ospUser', to=settings.AUTH_USER_MODEL, verbose_name='Petugas OSP')),
                ('rincianWorkorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rincianProgress', to='workorder.wo_progress', verbose_name='Rincian Progress')),
            ],
            options={
                'verbose_name': 'rincian',
                'verbose_name_plural': 'rincians',
            },
        ),
    ]
