# Generated by Django 3.1.3 on 2020-12-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wo_rincian',
            old_name='rincianWorkorder',
            new_name='rincianProgress',
        ),
        migrations.RemoveField(
            model_name='wo_day',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='wo_description',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='wo_progress',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='wo_rincian',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='wo_workorder',
            name='isActive',
        ),
        migrations.AddField(
            model_name='wo_day',
            name='isDelete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete'),
        ),
        migrations.AddField(
            model_name='wo_description',
            name='area',
            field=models.CharField(blank=True, choices=[('Lt.UG', 'Lt.UG'), ('Lt.1', 'Lt.1'), ('Lt.2', 'Lt.2'), ('Lt.3', 'Lt.3'), ('Lt.4', 'Lt.4'), ('Lt.5', 'Lt.5'), ('Lt.6', 'Lt.6'), ('Lt.7', 'Lt.7'), ('Lt.8', 'Lt.8'), ('Lt.9', 'Lt.9')], max_length=20, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='wo_description',
            name='categoryService',
            field=models.CharField(blank=True, choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Security', 'Security'), ('Cleaning', 'Cleaning'), ('Sivil/Architectur', 'Sivil/Architectur'), ('Electronics', 'Electronics'), ('Others', 'Others')], max_length=20, null=True, verbose_name='Category Service'),
        ),
        migrations.AddField(
            model_name='wo_description',
            name='isDelete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete'),
        ),
        migrations.AddField(
            model_name='wo_progress',
            name='isDelete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete'),
        ),
        migrations.AddField(
            model_name='wo_rincian',
            name='isDelete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete'),
        ),
        migrations.AddField(
            model_name='wo_workorder',
            name='isDelete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete'),
        ),
    ]
