# Generated by Django 3.1.3 on 2020-12-15 07:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_auto_20201214_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wo_description',
            name='area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lt.0', 'Lt.UG'), ('Lt.1', 'Lt.1'), ('Lt.2', 'Lt.2'), ('Lt.3', 'Lt.3'), ('Lt.4', 'Lt.4'), ('Lt.5', 'Lt.5'), ('Lt.6', 'Lt.6'), ('Lt.7', 'Lt.7'), ('Lt.8', 'Lt.8'), ('Lt.9', 'Lt.9')], max_length=20, null=True, verbose_name='Area'),
        ),
    ]
