# Generated by Django 3.1.3 on 2020-12-16 08:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_auto_20201216_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wo_description',
            name='area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lt.UG', 'Lt.UG'), ('Lt.1', 'Lt.1'), ('Lt.2', 'Lt.2'), ('Lt.3', 'Lt.3'), ('Lt.4', 'Lt.4'), ('Lt.5', 'Lt.5'), ('Lt.6', 'Lt.6'), ('Lt.7', 'Lt.7'), ('Lt.8', 'Lt.8'), ('Lt.9', 'Lt.9')], max_length=50, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='wo_description',
            name='categoryService',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Security', 'Security'), ('Cleaning', 'Cleaning'), ('Sivil/Architectur', 'Sivil/Architectur'), ('Electronics', 'Electronics'), ('Others', 'Others')], max_length=76, null=True, verbose_name='Category Service'),
        ),
    ]
