# Generated by Django 3.1.3 on 2020-11-24 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cln_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaArea', models.CharField(max_length=100, unique=True, verbose_name='Nama Area')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='cln_latest_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.DateField(verbose_name='History')),
            ],
            options={
                'verbose_name': 'history',
                'verbose_name_plural': 'histories',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='cln_subarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaSubarea', models.CharField(max_length=100, verbose_name='Nama Subarea')),
                ('namaAreaSubarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namaAreaSubarea', to='cleaning.cln_area', verbose_name='Nama Area')),
            ],
            options={
                'verbose_name': 'subarea',
                'verbose_name_plural': 'subareas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='cln_default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultKondisi', models.CharField(blank=True, choices=[('Tidak Bersih', 'Tidak Bersih'), ('Bersih', 'Bersih')], default='', max_length=50, null=True, verbose_name='Kondisi')),
                ('defaultKeterangan', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Keterangan')),
                ('defaultHasilTemuan', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Hasil Temuan')),
                ('defaultSubarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defaultSubarea', to='cleaning.cln_subarea', verbose_name='Nama Subarea')),
            ],
            options={
                'verbose_name': 'default',
                'verbose_name_plural': 'defaults',
            },
        ),
        migrations.CreateModel(
            name='cln_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hariIni', models.DateField(verbose_name='Hari ini')),
                ('clnChecker', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'checker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clnChecker', to=settings.AUTH_USER_MODEL, verbose_name="Checker's Signature")),
                ('clnMaker', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'maker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clnMaker', to=settings.AUTH_USER_MODEL, verbose_name="Maker's Signature")),
                ('clnSigner', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'signer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clnSigner', to=settings.AUTH_USER_MODEL, verbose_name="Signer's Signature")),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
            },
        ),
        migrations.CreateModel(
            name='cln_daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hariIni', models.DateField(verbose_name='Hari ini')),
                ('kondisi', models.CharField(blank=True, choices=[('Tidak Bersih', 'Tidak Bersih'), ('Bersih', 'Bersih')], default='', max_length=50, null=True, verbose_name='Kondisi')),
                ('keterangan', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Keterangan')),
                ('hasilTemuan', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Hasil Temuan')),
                ('done', models.DateTimeField(blank=True, null=True, verbose_name='Terlaksana Pada')),
                ('dailySubarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailySubarea', to='cleaning.cln_subarea', verbose_name='Nama Subarea')),
            ],
            options={
                'verbose_name': 'daily',
                'verbose_name_plural': 'dailies',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
