# Generated by Django 3.1.3 on 2020-11-24 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cln_day',
            name='clnChecker',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'checker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clnChecker', to=settings.AUTH_USER_MODEL, verbose_name="Checker's Signature"),
        ),
        migrations.AddField(
            model_name='cln_day',
            name='clnMaker',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'maker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clnMaker', to=settings.AUTH_USER_MODEL, verbose_name="Maker's Signature"),
        ),
        migrations.AddField(
            model_name='cln_day',
            name='clnSigner',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'signer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clnSigner', to=settings.AUTH_USER_MODEL, verbose_name="Signer's Signature"),
        ),
        migrations.AddField(
            model_name='cln_daily',
            name='dailySubarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailySubarea', to='cleaning.cln_subarea', verbose_name='Nama Subarea'),
        ),
    ]
