# Generated by Django 3.1.3 on 2021-07-26 06:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mendc_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaArea', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nama Area')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('isDelete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete')),
                ('createAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Create At')),
                ('deleteAt', models.DateTimeField(blank=True, default=datetime.datetime(2050, 12, 31, 16, 59, 59, tzinfo=utc), null=True, verbose_name='Delete At')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='mendc_latest_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.DateField(verbose_name='History')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('isDelete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete')),
                ('createAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Create At')),
                ('deleteAt', models.DateTimeField(blank=True, default=datetime.datetime(2050, 12, 31, 16, 59, 59, tzinfo=utc), null=True, verbose_name='Delete At')),
            ],
            options={
                'verbose_name': 'history',
                'verbose_name_plural': 'histories',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='mendc_subarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaSubarea', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Subarea')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('isDelete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete')),
                ('createAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Create At')),
                ('deleteAt', models.DateTimeField(blank=True, default=datetime.datetime(2050, 12, 31, 16, 59, 59, tzinfo=utc), null=True, verbose_name='Delete At')),
                ('namaAreaSubarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namaAreaSubarea', to='menondc.mendc_area', verbose_name='Nama Area')),
            ],
            options={
                'verbose_name': 'subarea',
                'verbose_name_plural': 'subareas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='mendc_default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultKondisi', models.CharField(blank=True, choices=[('Ok', 'Ok'), ('Not Ok', 'Not Ok')], default='', max_length=50, null=True, verbose_name='Kondisi')),
                ('defaultKeterangan', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Keterangan')),
                ('defaultHasilTemuan', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Hasil Temuan')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('isDelete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete')),
                ('createAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Create At')),
                ('deleteAt', models.DateTimeField(blank=True, default=datetime.datetime(2050, 12, 31, 16, 59, 59, tzinfo=utc), null=True, verbose_name='Delete At')),
                ('defaultSubarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defaultSubarea', to='menondc.mendc_subarea', verbose_name='Nama Subarea')),
            ],
            options={
                'verbose_name': 'default',
                'verbose_name_plural': 'defaults',
            },
        ),
        migrations.CreateModel(
            name='mendc_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hariIni', models.DateField(verbose_name='Hari ini')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('isDelete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete')),
                ('createAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Create At')),
                ('deleteAt', models.DateTimeField(blank=True, default=datetime.datetime(2050, 12, 31, 16, 59, 59, tzinfo=utc), null=True, verbose_name='Delete At')),
                ('mendcChecker', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'checker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mendcChecker', to=settings.AUTH_USER_MODEL, verbose_name="Checker's Signature")),
                ('mendcCheckerDispo', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'checker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mendcCheckerDispo', to=settings.AUTH_USER_MODEL, verbose_name='Disposisi Checker')),
                ('mendcMaker', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'maker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mendcMaker', to=settings.AUTH_USER_MODEL, verbose_name="Maker's Signature")),
                ('mendcMakerDispo', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'maker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mendcMakerDispo', to=settings.AUTH_USER_MODEL, verbose_name='Disposisi Maker')),
                ('mendcSigner', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'signer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mendcSigner', to=settings.AUTH_USER_MODEL, verbose_name="Signer's Signature")),
                ('mendcSignerDispo', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'signer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mendcSignerDispo', to=settings.AUTH_USER_MODEL, verbose_name='Disposisi Signer')),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
            },
        ),
        migrations.CreateModel(
            name='mendc_daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hariIni', models.DateField(verbose_name='Hari ini')),
                ('kondisi', models.CharField(blank=True, choices=[('Ok', 'Ok'), ('Not Ok', 'Not Ok')], default='', max_length=50, null=True, verbose_name='Kondisi')),
                ('keterangan', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Keterangan')),
                ('hasilTemuan', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Hasil Temuan')),
                ('done', models.DateTimeField(blank=True, null=True, verbose_name='Terlaksana Pada')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('isDelete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Delete')),
                ('createAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Create At')),
                ('deleteAt', models.DateTimeField(blank=True, default=datetime.datetime(2050, 12, 31, 16, 59, 59, tzinfo=utc), null=True, verbose_name='Delete At')),
                ('dailyDay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyDay', to='menondc.mendc_day', verbose_name='Foreign Key to Day')),
                ('dailySubarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailySubarea', to='menondc.mendc_subarea', verbose_name='Nama Subarea')),
            ],
            options={
                'verbose_name': 'daily',
                'verbose_name_plural': 'dailies',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
