# Generated by Django 3.1.3 on 2020-11-24 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menondc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mendc_day',
            name='mendcChecker',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'checker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mendcChecker', to=settings.AUTH_USER_MODEL, verbose_name="Checker's Signature"),
        ),
        migrations.AddField(
            model_name='mendc_day',
            name='mendcMaker',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'maker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mendcMaker', to=settings.AUTH_USER_MODEL, verbose_name="Maker's Signature"),
        ),
        migrations.AddField(
            model_name='mendc_day',
            name='mendcSigner',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'signer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mendcSigner', to=settings.AUTH_USER_MODEL, verbose_name="Signer's Signature"),
        ),
        migrations.AddField(
            model_name='mendc_daily',
            name='dailySubarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailySubarea', to='menondc.mendc_subarea', verbose_name='Nama Subarea'),
        ),
    ]
